### ISSUE TITLE
Magic Beans Server Crashing Consistently

### ISSUE THREAD

**Issue by Yukondano2** [Yulife/Wanderlust-Reloaded#435] opened 2015-05-03 01:54 UTC
I'm here on behalf of Maxvallaire, the owner of the new Magic Beans server that popped up after the previous owner disappeared. The server is highly unstable, and we've done little to the pack. I believe we have Cauldron, but beyond I don't think we've added very many plugins at all, if any. Here is the crash report:

http://pastebin.com/n65vbC0b

If anyone can interpret this (I sure as hell can't) please help.

**Comment by belathus** [comment] 2015-05-03 13:03
Well, I'm not sure what is going on there. If you are using Cauldron, that could possibly be the cause, but it doesn't look like you are.

The error seems to be related to Witchery world gen. It is pointing to genning the wall structure, and it can't find the block it is supposed to use to generate the wall. I've seen plenty of walls generate, so I'm not sure why you're having this specific problem.

Fastcraft is referenced -- I do not know if that means anything, but you can try temporarily removing it to see if that stops the crash.

**Comment by Krystallus** [comment] 2015-05-03 14:29
This is Max, i fixed it by disabling Fastcraft, it is incompatible with Cauldron, thanks for letting me know it was causing problems.

**Comment by belathus** [comment] 2015-05-03 19:15
Gotcha. I'll go ahead and close this issue then.

**Closed by belathus** 2015-05-03 19:15 UTC
